# Set term colors script - Generated by hellwal

# Colors from 0-15
printf "\033]4;0;#120c0b\033\\"
printf "\033]4;1;#5f352e\033\\"
printf "\033]4;2;#7b472e\033\\"
printf "\033]4;3;#815c44\033\\"
printf "\033]4;4;#836450\033\\"
printf "\033]4;5;#8b664a\033\\"
printf "\033]4;6;#827c75\033\\"
printf "\033]4;7;#ffdda5\033\\"
printf "\033]4;8;#4b322f\033\\"
printf "\033]4;9;#764239\033\\"
printf "\033]4;10;#995839\033\\"
printf "\033]4;11;#a17355\033\\"
printf "\033]4;12;#a37d64\033\\"
printf "\033]4;13;#ad7f5c\033\\"
printf "\033]4;14;#a29b92\033\\"
printf "\033]4;15;#ffffdc\033\\"

# Background
printf "\033]11;#120c0b\033\\";

# Foreground
printf "\033]10;#ffffdc\033\\";

# Cursor
printf "\033]12;#ffffdc\033\\";

# Border
printf "\033]7044;#ffffdc\033\\";
