# Generated by hellwal

wallpaper='/home/f1la/Pictures/lw/lwalpapers/wallpapers/b-029.jpg'

background='120c0b'
foreground='ffffdc'
cursor='ffffdc'
border='ffffdc'

color0='120c0b'
color1='5f352e'
color2='7b472e'
color3='815c44'
color4='836450'
color5='8b664a'
color6='827c75'
color7='ffdda5'
color8='4b322f'
color9='764239'
color10='995839'
color11='a17355'
color12='a37d64'
color13='ad7f5c'
color14='a29b92'
color15='ffffdc'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
