border_width=1

margin=4

default_border_color="#cccccc"       # Светло-серый цвет
focused_border_color="#aaaaaa"       # Нейтрально-серый цвет
floating_border_color="#888888"      # Темно-серый цвет
