#!/bin/bash

font="JetBrains Mono"  # Минималистичный моноширинный шрифт
bg_color="#1d1f2110"    # Фон панели (тёмный)
fg_color="#FFFFFF"      # Основной цвет текста (серый)
highlight_color="#ff79c6" # Цвет выделения фона для активного рабочего пространства

workspaces=("[web]" "[term]" "[code]" "[4]" "[5]" "[6]" "[7]" "[8]" "[9]")

get_volume() {
    volume=$(pactl get-sink-volume @DEFAULT_SINK@ | awk '{print $5}')
    muted=$(pactl get-sink-mute @DEFAULT_SINK@ | awk '{print $2}')
    
    if [[ "$muted" == "yes" ]]; then
        echo "MUTED"
    else
        echo "$volume"
    fi
}

get_datetime() {
    date "+%Y-%m-%d %H:%M:%S"
}

get_bitcoin_price() {
    bitcoin_price=$(curl -s https://api.coindesk.com/v1/bpi/currentprice/BTC.json | jq -r '.bpi.USD.rate')
    echo "$bitcoin_price"
}

# Функция для получения текущей раскладки клавиатуры
get_keyboard_layout() {
    layout=$(setxkbmap -query | grep layout | awk '{print $2}')
    if [[ "$layout" == "us" ]]; then
        echo "EN"  # Английская раскладка
    elif [[ "$layout" == "ru" ]]; then
        echo "RU"  # Русская раскладка
    else
        echo "$layout"  # Любая другая раскладка
    fi
}

# Запуск основного цикла
while true; do
    # Определяем активный рабочий стол
    active_workspace=$(xdotool get_desktop)

    # Формируем строку для отображения рабочих пространств с подсветкой фона
    workspace_output=""
    for i in "${!workspaces[@]}"; do
        if [ "$i" -eq "$active_workspace" ]; then
            # Подсвечиваем только фон под активным рабочим пространством
            workspace_output+="%{B$highlight_color}%{F$fg_color}${workspaces[i]}%{F-}%{B-} "  
        else
            # Для неактивных рабочих пространств фон прозрачный (не задаём цвет фона)
            workspace_output+="%{F$fg_color}${workspaces[i]} "
        fi
    done

    # Получаем статус звука, дату/время, курс биткойна, раскладку клавиатуры
    volume=$(get_volume)
    datetime=$(get_datetime)
    bitcoin=$(get_bitcoin_price)
    keyboard_layout=$(get_keyboard_layout)

    # Формирование минималистичного вывода
    echo -e "%{l}$workspace_output%{c}$datetime%{r}$keyboard_layout | $bitcoin | $volume"
    sleep 1  # Ожидание 1 секунду перед обновлением
done | lemonbar -g "1920x20+0+0" -B "$bg_color" -F "$fg_color" -f "$font"
