#!/bin/bash

font="JetBrains Mono"  # Минималистичный моноширинный шрифт
bg_color="#192141"   # Фон панели (чёрный с 80% прозрачности)
fg_color="#c5c7cf"     # Основной цвет текста (белый)
highlight_color="#53689C" # Цвет выделения фона для активного рабочего пространства

workspaces=(" 1 " " 2 " " 3 " " 4 " " 5 " " 6 " " 7 " " 8 " " 9 ")

get_volume() {
    volume=$(pactl get-sink-volume @DEFAULT_SINK@ | awk '{print $5}')
    muted=$(pactl get-sink-mute @DEFAULT_SINK@ | awk '{print $2}')
    
    if [[ "$muted" == "yes" ]]; then
        echo "MUTED"
    else
        echo "$volume"
    fi
}

get_datetime() {
    date "+%Y-%m-%d %H:%M:%S"
}

get_bitcoin_price() {
    bitcoin_price=$(curl -s https://api.coindesk.com/v1/bpi/currentprice/BTC.json | jq -r '.bpi.USD.rate')
    echo "$bitcoin_price"
}

get_keyboard_layout() {
    layout=$(xkb-switch 2>/dev/null)
    if [[ $? -ne 0 || -z "$layout" ]]; then
        echo "Unknown"  # В случае ошибки
        return 1
    fi

    case "$layout" in
        "us")
            echo "EN"
            ;;
        "ru")
            echo "RU"
            ;;
        "de")
            echo "DE"
            ;;
        "fr")
            echo "FR"
            ;;
        *)
            echo "$layout"  # Отображение оригинального кода, если нет описания
            ;;
    esac
}

# Запуск основного цикла
while true; do
    # Определяем активный рабочий стол
    active_workspace=$(xdotool get_desktop)

    # Формируем строку для отображения рабочих пространств с подсветкой фона
    workspace_output=""
    for i in "${!workspaces[@]}"; do
        if [ "$i" -eq "$active_workspace" ]; then
            workspace_output+="%{B$highlight_color}%{F$fg_color}${workspaces[i]}%{F-}%{B-} "  
        else
            workspace_output+="%{F$fg_color}${workspaces[i]} "
        fi
    done

    # Получаем статус звука, дату/время, курс биткойна, раскладку клавиатуры
    volume=$(get_volume)
    datetime=$(get_datetime)
    bitcoin=$(get_bitcoin_price)
    keyboard_layout=$(get_keyboard_layout)

    # Формирование минималистичного вывода
    echo -e "%{l} $workspace_output%{c}$datetime%{r}[$keyboard_layout] [$bitcoin] [$volume] "
    sleep 0.2  # Ожидание 200 мс перед обновлением
done | lemonbar -g "1910x20+5+2" -B "$bg_color" -F "$fg_color" -f "$font"
