#!/bin/sh

# Папка с обоями
WALLPAPER_DIR="/home/filla/wallpapers/wallpapers"

# Проверка папки с обоями
if [ ! -d "$WALLPAPER_DIR" ]; then
  echo "Error: Папка с обоями ($WALLPAPER_DIR) не найдена!"
  exit 1
fi

# Выбор случайного файла из папки
RANDOM_WALLPAPER=$(find "$WALLPAPER_DIR" -type f \( -iname "*.jpg" -o -iname "*.png" -o -iname "*.jpeg" \) | shuf -n 1)

# Проверка, есть ли обои
if [ -z "$RANDOM_WALLPAPER" ]; then
  echo "Error: Нет доступных обоев в папке $WALLPAPER_DIR"
  echo "Содержимое папки: $(ls $WALLPAPER_DIR)"
  exit 1
fi

# Установить обои
nitrogen --set-zoom-fill "$RANDOM_WALLPAPER"
echo "Установлены обои: $RANDOM_WALLPAPER"

# Генерация цветов
echo "Генерация цветовой схемы..."
hellwal -i "$RANDOM_WALLPAPER"

echo "Копирование конфигурационный файлов"

# cp config to cava `
cp -r .cache/hellwal/config .config/cava/config

cat .config/dunst/dunstrc.tmp .cache/hellwal/dunstrc > .config/dunst/dunstrc

echo "Перезапуск сервисов"

# restart services with new color configs 
pkill polybar 
nohup polybar & 

pkill cava 
pkill dunst

dunst &
