[colors.primary]
background = "#%% background.hex %%"
foreground = "#%% foreground.hex %%"

[colors.cursor]
text = "#%% color15.hex %%"
cursor = "#%% cursor.hex %%"

[colors.vi_mode_cursor]
text = "#%% color15.hex %%"
cursor = "#%% cursor.hex %%"

[colors.search.matches]
foreground = "#1e1d1c"
background = "#c6c6c6"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
background = "#%% background.hex %%"
foreground = "#%% foreground.hex %%"

[colors.selection]
text = "#%% color15.hex %%"
background = "CellForeground"

[colors.normal]
black = "#%% color0.hex %%"
red = "#%% color1.hex %%"
green = "#%% color2.hex %%"
yellow = "#%% color3.hex %%"
blue = "#%% color4.hex %%"
magenta = "#%% color5.hex %%"
cyan = "#%% color6.hex %%"
white = "#%% color7.hex %%"

[colors.bright]
black = "#%% color8.hex %%"
red = "#%% color9.hex %%"
green = "#%% color10.hex %%"
yellow = "#%% color11.hex %%"
blue = "#%% color12.hex %%"
magenta = "#%% color13.hex %%"
cyan = "#%% color14.hex %%"
white = "#%% color15.hex %%"

[colors.dim]
black = "#%% color0.hex %%"
red = "#%% color1.hex %%"
green = "#%% color2.hex %%"
yellow = "#%% color3.hex %%"
blue = "#%% color4.hex %%"
magenta = "#%% color5.hex %%"
cyan = "#%% color6.hex %%"
white = "#%% color7.hex %%"

