theme = "base16_transparent"

[editor] 
line-number = "relative"
bufferline = "multiple"

[editor.cursor-shape] 
insert = "bar"

[keys.normal] 
esc = ["collapse_selection", "keep_primary_selection"] 
"C-s" = ":w" 
"C-q" = "save_selection"
y = "yank_to_clipboard"                   
p = "paste_clipboard_after"               
P = "paste_clipboard_before"              


[keys.insert] 
"C-a" = "normal_mode"
